apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-prod
spec:
  acme:
    email: dissh33@yandex.ru
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: prod-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx