pipeline {

  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: docker
            image: docker:latest
            command:
            - cat
            tty: true
            volumeMounts:
             - mountPath: /var/run/docker.sock
               name: docker-sock
          volumes:
          - name: docker-sock
            hostPath:
              path: /var/run/docker.sock    
        '''
    }
  }
  
  stages {

    stage ('Clean Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Clone') {
      steps {
        container('docker') {
          git branch: 'dev', changelog: false, poll: false, url: 'https://github.com/dissh33/Klondike-TR'
          sh 'pwd'
          sh 'ls'
          sh 'cd /home/jenkins/agent/workspace/items_build_test/src/Items/Items.Admin'
          sh 'pwd'
          sh 'ls'
          sh 'docker build src/Items/Items.Admin/Dockerfile -t dissh33/items-sevice'
          sh 'pwd'
          sh 'ls'
        }
      }
    }

    stage ('Docker Build') {
      steps {
        container('docker') {
          sh 'pwd'
        }
      }
    }

  }
}