apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-staging
spec:
  acme:
    email: dissh33@yandex.ru
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: staging-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx